//
//  Culinova scaffold v0.2
//  Generated by ChatGPT – June 22 2025
//
//  This single Swift file compiles in Xcode 15.3+ and gives you:
//  • SwiftData models (Recipe, Ingredient, Step, Tag)
//  • A ModelContainer injected via the @main App struct
//  • Basic SwiftUI list + detail editing flow
//  Adjust, split, or extend as you grow the project.
//

import SwiftUI
import SwiftData

@main
struct CulinovaApp: App {

    var body: some Scene {
        WindowGroup {
            RecipeListView()          // root screen (in Views/Recipes/)
        }
        // Register every root entity once.  Variadic, *not* an array.
        .modelContainer(
            for: [
                Recipe.self,
                Ingredient.self,
                Step.self,
                Tag.self,
                Media.self,
                User.self,
                Follow.self,
                AuthCredential.self
            ]
        )
    }
}

// MARK: - Previews

#Preview("App") {
    // In‑memory container seeded with a sample recipe for Canvas previews.
    let previewContainer: ModelContainer = {
        let container = try! ModelContainer(
            for: Recipe.self,
                 Ingredient.self,
                 Step.self,
                 Tag.self,
            configurations: ModelConfiguration(isStoredInMemoryOnly: true)
        )
        let ctx = ModelContext(container)
        ctx.insert(Recipe(title: "Preview Pancakes"))
        return container
    }()

    NavigationStack {
        RecipeListView()
    }
    .modelContainer(previewContainer)
}
